"use client";

import localFont from "next/font/local";
import "./globals.css";
import { DynamicContextProvider } from "@dynamic-labs/sdk-react-core";
import { EthereumWalletConnectors } from "@dynamic-labs/ethereum";
import { GlobalWalletExtension } from "@dynamic-labs/global-wallet";
import { useState } from "react";
import Modal from "./components/Modal";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/images/story_icon.svg',
  },
};

const evmNetworks = [{
  blockExplorerUrls: ['https://testnet.storyscan.xyz/'],
  chainId: 1513,
  chainName: 'Story Protocol',
  iconUrls: ["/images/story_icon.svg"],
  name: 'Story',
  nativeCurrency: {
    decimals: 18,
    name: 'IP',
    symbol: 'IP',
  },
  networkId: 1513,
  rpcUrls: ['https://testnet.storyrpc.io/'],
  vanityName: 'Story',
}];

const FUNDING_AMOUNT = 5; // Set the funding amount here

async function fundNewWallet(walletAddress, setModalOpen, setTransactionHash) {
  try {
    const response = await fetch('/api/fund-wallet', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ walletAddress, amount: FUNDING_AMOUNT }),
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.message || 'An error occurred');
    }

    console.log('Transaction successful:', data);
    setTransactionHash(data.transactionHash);
    setModalOpen(true);
    return;
  } catch (error) {
    console.error('Error sending funds:', error);
    throw error;
  }
}

export default function RootLayout({ children }) {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [transactionHash, setTransactionHash] = useState('');

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/story_icon.svg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DynamicContextProvider
          settings={{
            events: {
              onEmbeddedWalletCreated: (jwtVerifiedCredential) => {
                console.log('onEmbeddedWalletCreated', jwtVerifiedCredential)
                fundNewWallet(jwtVerifiedCredential.address, setIsModalOpen, setTransactionHash)
              }
            },
            environmentId: "2995b456-45c1-4326-af24-5f9fca2214cf",
            walletConnectors: [EthereumWalletConnectors],
            walletConnectorExtensions: [GlobalWalletExtension],
            overrides: {
              evmNetworks
            },
          }}
        >
          {children}
          <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} transactionHash={transactionHash}>
            <h2>Wallet Funded!</h2>
            <p>We just funded your new wallet with {FUNDING_AMOUNT} IP!</p>
          </Modal>
        </DynamicContextProvider>
      </body>
    </html>
  );
}
